# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 500, 480))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(510, 10, 281, 461))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.urlEdit = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.urlEdit.setFont(font)
        self.urlEdit.setObjectName("urlEdit")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameBox = QtWidgets.QComboBox(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.nameBox.setFont(font)
        self.nameBox.setEditable(True)
        self.nameBox.setObjectName("nameBox")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.numEdit = QtWidgets.QLineEdit(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.numEdit.setFont(font)
        self.numEdit.setText("")
        self.numEdit.setClearButtonEnabled(True)
        self.numEdit.setObjectName("numEdit")
        self.B_uid = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_uid.setFont(font)
        self.B_uid.setObjectName("B_uid")
        self.B_internet = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_internet.setFont(font)
        self.B_internet.setObjectName("B_internet")
        self.B_ethernet = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_ethernet.setFont(font)
        self.B_ethernet.setObjectName("B_ethernet")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.B_internet.clicked.connect(MainWindow.internet)
        self.B_ethernet.clicked.connect(MainWindow.ethernet)
        self.B_uid.clicked.connect(MainWindow.uid)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "内部网地址"))
        self.label.setText(_translate("MainWindow", "姓名"))
        self.label_2.setText(_translate("MainWindow", "身份证号"))
        self.B_uid.setText(_translate("MainWindow", "破解加密"))
        self.B_internet.setText(_translate("MainWindow", "手机版"))
        self.B_ethernet.setText(_translate("MainWindow", "电脑版"))

