# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 320, 261))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.urlEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.urlEdit.setGeometry(QtCore.QRect(340, 10, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.urlEdit.setFont(font)
        self.urlEdit.setObjectName("urlEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 50, 48, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.nameBox = QtWidgets.QComboBox(self.centralwidget)
        self.nameBox.setGeometry(QtCore.QRect(340, 90, 300, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.nameBox.setFont(font)
        self.nameBox.setEditable(True)
        self.nameBox.setObjectName("nameBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 138, 96, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.numEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.numEdit.setGeometry(QtCore.QRect(340, 179, 300, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.numEdit.setFont(font)
        self.numEdit.setClearButtonEnabled(True)
        self.numEdit.setObjectName("numEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 227, 48, 27))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.kindBox = QtWidgets.QComboBox(self.centralwidget)
        self.kindBox.setGeometry(QtCore.QRect(10, 310, 631, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.kindBox.setFont(font)
        self.kindBox.setObjectName("kindBox")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(670, 60, 121, 283))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.B_wechat = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_wechat.setFont(font)
        self.B_wechat.setObjectName("B_wechat")
        self.verticalLayout.addWidget(self.B_wechat)
        self.B_firefox = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_firefox.setFont(font)
        self.B_firefox.setObjectName("B_firefox")
        self.verticalLayout.addWidget(self.B_firefox)
        self.B_driver = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_driver.setFont(font)
        self.B_driver.setObjectName("B_driver")
        self.verticalLayout.addWidget(self.B_driver)
        self.B_npcap = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_npcap.setFont(font)
        self.B_npcap.setObjectName("B_npcap")
        self.verticalLayout.addWidget(self.B_npcap)
        self.B_uid = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_uid.setFont(font)
        self.B_uid.setObjectName("B_uid")
        self.verticalLayout.addWidget(self.B_uid)
        self.B_internet = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_internet.setFont(font)
        self.B_internet.setObjectName("B_internet")
        self.verticalLayout.addWidget(self.B_internet)
        self.B_ethernet = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.B_ethernet.setFont(font)
        self.B_ethernet.setObjectName("B_ethernet")
        self.verticalLayout.addWidget(self.B_ethernet)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.B_wechat.clicked.connect(MainWindow.wechat)
        self.B_firefox.clicked.connect(MainWindow.firefox)
        self.B_driver.clicked.connect(MainWindow.driver)
        self.B_internet.clicked.connect(MainWindow.internet)
        self.B_ethernet.clicked.connect(MainWindow.ethernet)
        self.B_uid.clicked.connect(MainWindow.uid)
        self.B_npcap.clicked.connect(MainWindow.npcap)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.urlEdit.setText(_translate("MainWindow", "http://10.99.108.43:81/Login/YT_Login2"))
        self.label.setText(_translate("MainWindow", "姓名"))
        self.label_2.setText(_translate("MainWindow", "身份证号"))
        self.label_3.setText(_translate("MainWindow", "职名"))
        self.B_wechat.setText(_translate("MainWindow", "安装微信"))
        self.B_firefox.setText(_translate("MainWindow", "安装火狐"))
        self.B_driver.setText(_translate("MainWindow", "安装驱动"))
        self.B_npcap.setText(_translate("MainWindow", "破解工具"))
        self.B_uid.setText(_translate("MainWindow", "破解加密"))
        self.B_internet.setText(_translate("MainWindow", "手机版"))
        self.B_ethernet.setText(_translate("MainWindow", "电脑版"))

